AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Valida o usuário e senha e gera o token jwt
Resources:
  login:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: Valida o usuário e senha e gera o token jwt
      MemorySize: 128
      Timeout: 3
      Role: ''
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /login
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - 
        SubnetIds:
          - 
      Environment:
        Variables:
          LOGIN_AUTH_SQS: ''
          TABLE_NAME_CUSTOMER: customer
      Layers:
        - ''
